language: node_js
node_js: '8'
services:
- postgresql
before_script:
- psql -c 'create database maps;' -U postgres
- psql -c 'create database maps_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 
  app: travis-test-penguins
  skip_cleanup: true